###
POST http://localhost:3030/api/users/register HTTP/1.1
content-type: application/json

{
    "email": "gabariel@test.com",
    "password": "Gabriel123"
}


###
POST http://localhost:3030/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "gabariel@test.com",
    "password": "Gabriel123"
}

###
POST http://localhost:3030/api/tickets/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjQzNjczYmZmOTk3Yzk2ZmI4NGU3ZSIsImVtYWlsIjoiZ2FiYXJpZWxAdGVzdC5jb20iLCJpYXQiOjE3MTM2NDkyNzAsImV4cCI6MTcyMjI4OTM2OX0.qF-rmFjLeNIggW4XNyIZZebWF_Jg7L-YzB2OnirO5U0

    {
        "tickets": [
            {
                "ticketId": 1,
                "price": 25000.00,
                "selectedNumbers": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
            },
            {
                "ticketId": 2,
                "price": 15000.00,
                "selectedNumbers": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
            }
                     
        ]
    }
